In [41]:
## identifying the character fo alphabets

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn import svm

In [42]:
letter_df=pd.read_csv("letterdata.csv")

In [43]:
letter_df.head()

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10

In [51]:
clf=svm.SVC(gamma=0.025, C=3)

In [52]:
X,y=np.array(letter_df)[:,1:16],np.array(letter_df.letter)[:]

In [53]:
X_train, X_test, y_train,y_test =train_test_split(X,y,test_size=.3,random_state=1) 
# test data will be about 30%
# random state to be 1 in order to keep 70:30 ratio to be same.

In [54]:
clf.fit(X_train,y_train)
#26 different surfaces/support vector machine will be created in mathematical space.

SVC(C=3, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.025, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [55]:
clf.score(X_test,y_test)

0.9615

In [49]:
y_predict=clf.predict(X_test)

In [50]:
pd.crosstab(y_test,y_predict)

col_0,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
row_0,,,,,,,,,,,,,,,,,,,,,
A,232,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
B,0,230,0,1,1,1,0,0,0,1,...,0,4,2,0,0,1,0,0,0,0
C,0,0,223,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
D,0,2,0,224,0,1,1,1,0,0,...,0,2,0,0,0,0,0,0,0,0
E,0,1,0,0,208,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,2
F,0,0,0,0,2,212,0,0,2,0,...,0,0,0,0,0,2,0,0,0,0
G,0,1,3,0,5,0,215,0,0,0,...,0,0,0,0,0,1,2,0,0,0
H,0,1,0,6,0,0,1,213,0,0,...,0,7,0,0,2,0,0,0,0,0
I,0,0,0,0,0,5,0,0,188,5,...,0,0,0,0,0,0,0,1,0,0
J,0,0,0,0,0,0,1,1,10,187,...,0,0,0,0,0,0,0,0,0,0
K,0,2,0,2,0,0,0,2,0,0,...,0,3,0,0,0,0,0,1,0,0
L,0,1,0,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
M,0,3,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,1,0,0,0
N,0,2,0,6,0,0,0,1,0,0,...,0,2,0,0,0,3,0,0,0,0
O,0,0,2,5,0,0,0,0,0,0,...,2,0,0,0,1,0,0,0,0,0
P,0,1,0,1,0,15,0,2,0,0,...,0,2,0,0,0,0,0,0,1,0
Q,0,0,0,0,0,0,1,0,0,0,...,231,0,0,0,1,0,0,0,0,0
R,0,7,0,2,1,0,0,1,0,0,...,1,203,0,0,0,0,0,0,0,0
S,0,0,0,0,1,1,0,0,0,0,...,0,1,251,0,0,0,0,0,0,1
T,0,0,0,1,4,0,0,0,0,0,...,0,0,0,245,0,0,0,0,0,0
U,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,239,0,0,0,0,0
V,0,4,0,0,1,0,0,0,0,0,...,0,0,0,0,0,212,0,0,0,0
W,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,226,0,0,0
X,0,0,0,2,1,0,0,0,0,0,...,0,0,0,0,0,0,0,232,0,0
Y,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,1,252,0
Z,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,233